import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | PlebTest',
  description: 'Terms and conditions for using PlebTest AI-powered idea validation service.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-950 text-gray-100">
      {/* Header */}
      <header className="border-b border-gray-800">
        <div className="max-w-4xl mx-auto px-4 py-6">
          <Link
            href="/"
            className="text-orange-500 hover:text-orange-400 transition-colors inline-flex items-center gap-2"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            Back to Home
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-4 py-12">
        <h1 className="text-4xl font-bold text-white mb-2">Terms of Service</h1>
        <p className="text-gray-400 mb-12">Last updated: January 23, 2025</p>

        <div className="space-y-10">
          {/* Acceptance of Terms */}
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
            <div className="space-y-4 text-gray-300 leading-relaxed">
              <p>
                By accessing or using PlebTest (&quot;the Service&quot;), you agree to be bound by these Terms of
                Service (&quot;Terms&quot;). If you do not agree to all the terms and conditions, you may not
                access or use the Service.
              </p>
              <p>
                These Terms apply to all visitors, users, and others who access or use the Service.
                By using the Service, you represent that you are at least 18 years of age or have the
                consent of a parent or guardian.
              </p>
            </div>
          </section>

          {/* Description of Service */}
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">2. Description of Service</h2>
            <div className="space-y-4 text-gray-300 leading-relaxed">
              <p>
                PlebTest is an AI-powered idea validation platform that helps entrepreneurs and product
                builders test and validate their business ideas. The Service provides:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>AI-generated market analysis and feedback</li>
                <li>Simulated customer persona interviews</li>
                <li>Competitive landscape assessments</li>
                <li>Validation scores and recommendations</li>
              </ul>
              <p className="mt-4">
                The Service is designed to provide insights and guidance, but should not be considered
                a substitute for professional business, legal, or financial advice.
              </p>
            </div>
          </section>

          {/* User Responsibilities */}
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">3. User Responsibilities</h2>
            <div className="space-y-4 text-gray-300 leading-relaxed">
              <p>When using the Service, you agree to:</p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Provide accurate and complete information when required</li>
                <li>Use the Service only for lawful purposes</li>
                <li>Not attempt to interfere with or disrupt the Service</li>
                <li>Not use the Service to generate harmful, illegal, or deceptive content</li>
                <li>Not attempt to reverse engineer, decompile, or hack the Service</li>
                <li>Not use automated systems to access the Service without permission</li>
                <li>Maintain the confidentiality of any account credentials</li>
              </ul>
            </div>
          </section>

          {/* AI-Generated Content Disclaimer */}
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">4. AI-Generated Content Disclaimer</h2>
            <div className="space-y-4 text-gray-300 leading-relaxed">
              <div className="bg-gray-900 border border-orange-500/30 rounded-lg p-6">
                <p className="font-medium text-orange-400 mb-3">Important Notice About AI Results</p>
                <p>
                  The feedback, analysis, and recommendations provided by PlebTest are generated by
                  artificial intelligence systems. These outputs are <span className="font-medium text-white">simulations
                  and estimations</span>, not guarantees of real-world outcomes.
                </p>
              </div>
              <p className="mt-4">You acknowledge and understand that:</p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>
                  <span className="font-medium text-white">Results are simulated:</span> AI-generated
                  persona interviews and market analysis represent potential scenarios, not actual
                  customer feedback or market research.
                </li>
                <li>
                  <span className="font-medium text-white">No success guarantees:</span> Validation
                  scores and recommendations do not guarantee business success, market viability, or
                  financial returns.
                </li>
                <li>
                  <span className="font-medium text-white">AI limitations:</span> AI systems may produce
                  inaccurate, incomplete, or biased information. Results should be verified through
                  additional research and real-world testing.
                </li>
                <li>
                  <span className="font-medium text-white">Not professional advice:</span> The Service
                  does not provide legal, financial, investment, or professional business advice.
                </li>
                <li>
                  <span className="font-medium text-white">Decision responsibility:</span> You are
                  solely responsible for any business decisions made based on information from the Service.
                </li>
              </ul>
            </div>
          </section>

          {/* Intellectual Property */}
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">5. Intellectual Property</h2>
            <div className="space-y-4 text-gray-300 leading-relaxed">
              <p>
                <span className="font-medium text-white">Our Content:</span> The Service, including its
                original content, features, and functionality, is owned by PlebTest and is protected by
                international copyright, trademark, and other intellectual property laws.
              </p>
              <p>
                <span className="font-medium text-white">Your Content:</span> You retain ownership of any
                ideas, concepts, or business information you submit to the Service. By using the Service,
                you grant us a limited license to process your content solely for the purpose of providing
                the Service to you.
              </p>
              <p>
                <span className="font-medium text-white">AI Outputs:</span> You may use AI-generated
                outputs from the Service for your personal and business purposes. However, you acknowledge
                that similar outputs may be generated for other users with similar inputs.
              </p>
            </div>
          </section>

          {/* Payment Terms */}
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">6. Payment Terms</h2>
            <div className="space-y-4 text-gray-300 leading-relaxed">
              <p>
                Certain features of the Service may require payment. By selecting a paid plan, you agree to:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Pay all applicable fees as described at the time of purchase</li>
                <li>Provide accurate and complete payment information</li>
                <li>Authorize us to charge your payment method for recurring fees if applicable</li>
              </ul>
              <p className="mt-4">
                Refunds are handled on a case-by-case basis. Please contact us at{' '}
                <a href="mailto:support@plebtest.com" className="text-orange-500 hover:text-orange-400">
                  support@plebtest.com
                </a>{' '}
                for refund requests.
              </p>
            </div>
          </section>

          {/* Limitation of Liability */}
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">7. Limitation of Liability</h2>
            <div className="space-y-4 text-gray-300 leading-relaxed">
              <p>
                To the maximum extent permitted by applicable law, PlebTest and its officers, directors,
                employees, and agents shall not be liable for:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Any indirect, incidental, special, consequential, or punitive damages</li>
                <li>Any loss of profits, revenue, data, or business opportunities</li>
                <li>Any damages arising from your use of or inability to use the Service</li>
                <li>Any damages arising from decisions made based on AI-generated content</li>
                <li>Any unauthorized access to or alteration of your data</li>
              </ul>
              <p className="mt-4">
                Our total liability for any claims arising from or related to the Service shall not
                exceed the amount you paid us in the twelve (12) months preceding the claim.
              </p>
            </div>
          </section>

          {/* Disclaimer of Warranties */}
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">8. Disclaimer of Warranties</h2>
            <div className="space-y-4 text-gray-300 leading-relaxed">
              <p>
                The Service is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis without any warranties
                of any kind, either express or implied, including but not limited to:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Warranties of merchantability or fitness for a particular purpose</li>
                <li>Warranties that the Service will be uninterrupted, secure, or error-free</li>
                <li>Warranties regarding the accuracy or reliability of AI-generated content</li>
                <li>Warranties that the Service will meet your specific requirements or expectations</li>
              </ul>
            </div>
          </section>

          {/* Indemnification */}
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">9. Indemnification</h2>
            <div className="space-y-4 text-gray-300 leading-relaxed">
              <p>
                You agree to indemnify, defend, and hold harmless PlebTest and its officers, directors,
                employees, and agents from and against any claims, liabilities, damages, losses, and
                expenses arising out of or in any way connected with:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Your use of the Service</li>
                <li>Your violation of these Terms</li>
                <li>Your violation of any rights of another party</li>
                <li>Any business decisions you make based on the Service</li>
              </ul>
            </div>
          </section>

          {/* Termination */}
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">10. Termination</h2>
            <div className="space-y-4 text-gray-300 leading-relaxed">
              <p>
                We may terminate or suspend your access to the Service immediately, without prior notice
                or liability, for any reason, including but not limited to:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Breach of these Terms</li>
                <li>Fraudulent, abusive, or illegal activity</li>
                <li>Non-payment of applicable fees</li>
                <li>At our sole discretion for any other reason</li>
              </ul>
              <p className="mt-4">
                Upon termination, your right to use the Service will immediately cease. Provisions of
                these Terms that by their nature should survive termination shall survive, including
                ownership provisions, warranty disclaimers, indemnity, and limitations of liability.
              </p>
            </div>
          </section>

          {/* Changes to Terms */}
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">11. Changes to Terms</h2>
            <div className="space-y-4 text-gray-300 leading-relaxed">
              <p>
                We reserve the right to modify or replace these Terms at any time at our sole discretion.
                If a revision is material, we will provide at least 30 days&apos; notice prior to any new terms
                taking effect by posting the updated Terms on this page and updating the &quot;Last updated&quot; date.
              </p>
              <p>
                Your continued use of the Service after any changes to the Terms constitutes acceptance
                of those changes. If you do not agree to the new terms, please stop using the Service.
              </p>
            </div>
          </section>

          {/* Governing Law */}
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">12. Governing Law</h2>
            <div className="space-y-4 text-gray-300 leading-relaxed">
              <p>
                These Terms shall be governed by and construed in accordance with the laws of the
                jurisdiction in which PlebTest operates, without regard to its conflict of law provisions.
              </p>
              <p>
                Any disputes arising from or relating to these Terms or the Service shall be resolved
                through good faith negotiations. If negotiations fail, disputes shall be submitted to
                binding arbitration in accordance with applicable arbitration rules.
              </p>
            </div>
          </section>

          {/* Severability */}
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">13. Severability</h2>
            <div className="space-y-4 text-gray-300 leading-relaxed">
              <p>
                If any provision of these Terms is held to be unenforceable or invalid, such provision
                will be changed and interpreted to accomplish the objectives of such provision to the
                greatest extent possible under applicable law, and the remaining provisions will continue
                in full force and effect.
              </p>
            </div>
          </section>

          {/* Contact Information */}
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">14. Contact Information</h2>
            <div className="space-y-4 text-gray-300 leading-relaxed">
              <p>
                If you have any questions about these Terms of Service, please contact us at:
              </p>
              <p className="mt-4">
                <span className="font-medium text-white">Email:</span>{' '}
                <a href="mailto:support@plebtest.com" className="text-orange-500 hover:text-orange-400">
                  support@plebtest.com
                </a>
              </p>
            </div>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-800 mt-16">
        <div className="max-w-4xl mx-auto px-4 py-8">
          <div className="flex flex-col sm:flex-row justify-between items-center gap-4">
            <p className="text-gray-500 text-sm">
              © {new Date().getFullYear()} PlebTest. All rights reserved.
            </p>
            <div className="flex gap-6">
              <Link href="/privacy" className="text-gray-400 hover:text-orange-500 text-sm transition-colors">
                Privacy Policy
              </Link>
              <Link href="/" className="text-gray-400 hover:text-orange-500 text-sm transition-colors">
                Home
              </Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
